### ISSUE TITLE
GameUpdaterにおいて、CharacterのSaveChangesAsyncでSQL例外が出ることがある

### ISSUE THREAD

**Issue by kmycode** [kmycode/sangokukmy#413]
## ケース１：政務官（集合官）を解雇したとき

~~~
2019-03-25 11:00:19.7330||ERROR|SangokuKmy.Startup|更新処理中にエラーが発生しま>した Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '152' for key 'PRIMARY' ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '152' for key 'PRIMARY'
   at MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1245
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 59
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at SangokuKmy.Models.Data.MainRepository.SaveChangesAsync() in /codebuild/output/src328578182/src/SangokuKmy/Models/Data/MainRepository.cs:line 202
   at SangokuKmy.Models.Updates.GameUpdater.UpdateCharacterAsync(MainRepository repo, Character character) in /codebuild/output/src328578182/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 868
   at SangokuKmy.Models.Updates.GameUpdater.<>c__DisplayClass4_0.<<UpdateCharactersAsync>b__0>d.MoveNext() in /codebuild/output/src328578182/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 687
~~~

## ケース２：政務官を含む国が滅亡してから６時間後

~~~~
2019-04-06 08:09:39.1603||ERROR|SangokuKmy.Startup|更新処理中にエラーが発生しま>した System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe. This could also be caused by a nested query being evaluated on the client, if this is the case rewrite the query avoiding nested invocations.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at SangokuKmy.Models.Data.MainRepository.SaveChangesAsync() in /codebuild/output/src282748675/src/SangokuKmy/Models/Data/MainRepository.cs:line 208
   at SangokuKmy.Models.Updates.GameUpdater.UpdateCharacterAsync(MainRepository repo, Character character) in /codebuild/output/src282748675/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 954
   at SangokuKmy.Models.Updates.GameUpdater.<>c__DisplayClass5_0.<<UpdateCharactersAsync>b__0>d.MoveNext() in /codebuild/output/src282748675/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 707
--- End of stack trace from previous location where exception was thrown ---
   at SangokuKmy.Common.Optional`1.SomeAsync(Func`2 act) in /codebuild/output/src282748675/src/SangokuKmy/Common/Optional.cs:line 70
   at SangokuKmy.Models.Updates.GameUpdater.UpdateCharactersAsync(MainRepository repo, IReadOnlyCollection`1 characterIds) in /codebuild/output/src282748675/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 705
   at SangokuKmy.Models.Updates.GameUpdater.UpdateLoop() in /codebuild/output/src282748675/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 104
   at SangokuKmy.Models.Updates.GameUpdater.<>c__DisplayClass2_0.<<BeginUpdate>b__0>d.MoveNext() in /codebuild/output/src282748675/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 48|url: |action:
~~~~

## ケース３：政務官を解雇した時

~~~~
2019-04-20 16:19:51.3199||ERROR|SangokuKmy.Startup|更新処理中にエラーが発生しま>した Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '192' for key 'PRIMARY' ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '192' for key 'PRIMARY'

以下略
~~~~

**Comment by kmycode** [comment]
ケース２は #482 にて解決済

**Comment by kmycode** [comment]
ケース３では、政務官を将軍に任命していたが、そのデータも残っていた
