### ISSUE TITLE
更新エラー

### ISSUE THREAD

**Issue by kmycode** [kmycode/sangokukmy#482]
~~~~
2019-04-08 03:22:14.2514||ERROR|SangokuKmy.Startup|更新処理中にエラーが発生しま>した System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe. This could also be caused by a nested query being evaluated on the client, if this is the case rewrite the query avoiding nested invocations.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at SangokuKmy.Models.Data.MainRepository.SaveChangesAsync() in /codebuild/output/src979815793/src/SangokuKmy/Models/Data/MainRepository.cs:line 208
   at SangokuKmy.Models.Updates.GameUpdater.UpdateCharacterAsync(MainRepository repo, Character character) in /codebuild/output/src979815793/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 955
   at SangokuKmy.Models.Data.MainRepository.SaveChangesAsync() in /codebuild/output/src979815793/src/SangokuKmy/Models/Data/MainRepository.cs:line 208
   at SangokuKmy.Models.Updates.GameUpdater.UpdateCharacterAsync(MainRepository repo, Character character) in /codebuild/output/src979815793/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 955
   at SangokuKmy.Models.Updates.GameUpdater.<>c__DisplayClass5_0.<<UpdateCharactersAsync>b__0>d.MoveNext() in /codebuild/output/src979815793/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 708
--- End of stack trace from previous location where exception was thrown ---
   at SangokuKmy.Common.Optional`1.SomeAsync(Func`2 act) in /codebuild/output/src979815793/src/SangokuKmy/Common/Optional.cs:line 70
   at SangokuKmy.Models.Updates.GameUpdater.UpdateCharactersAsync(MainRepository repo, IReadOnlyCollection`1 characterIds) in /codebuild/output/src979815793/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 706


2019-04-08 07:50:01.3505||ERROR|SangokuKmy.Startup|更新処理中にエラーが発生しま>した System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
   at MySqlConnector.Core.ServerSession.StartQuerying(MySqlCommand command) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 149
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 33
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at MySql.Data.MySqlClient.MySqlTransaction.CommitAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlTransaction.cs:line 25
   at MySql.Data.MySqlClient.MySqlTransaction.Commit() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlTransaction.cs:line 12
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
   at SangokuKmy.Models.Data.MainRepository.Dispose() in /codebuild/output/src979815793/src/SangokuKmy/Models/Data/MainRepository.cs:line 194
   at SangokuKmy.Models.Updates.GameUpdater.UpdateLoop() in /codebuild/output/src979815793/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 104
   at SangokuKmy.Models.Updates.GameUpdater.<>c__DisplayClass2_0.<<BeginUpdate>b__0>d.MoveNext() in /codebuild/output/src979815793/src/SangokuKmy/Models/Updates/GameUpdater.cs:line 48|url: |action:


2019-04-08 07:50:31.4306||ERROR|SangokuKmy.Startup|更新処理中にエラーが発生しま>した System.InvalidOperationException: Connection must be Open; current state is Closed

~~~~

**Comment by kmycode** [comment]
対応した。経過観察のためしばらく残しとく
